name: "chaostoolkit ubuntu CI workflow"


on:
  push:
    branches: [ test ]

jobs:

# https://chaostoolkit.org/reference/usage/install/
  chaostoolkit-ubuntu-latest-job:
    name: "chaostoolkit on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "Install chaostoolkit"
      run: |
        # Install Python
        sudo apt-get install python3 python3-venv
        # Create a virtual environment
        python3 -m venv ~/.venvs/chaostk 
        source  ~/.venvs/chaostk/bin/activate  
        # Install the CLI
        # pip install -U chaostoolkit
        pip install -r requirements.txt
        chaos --version         
